### ISSUE TITLE
Feature Request: simple interface

### ISSUE THREAD

**Issue by onelivesleft** [SogoCZE/jai_parser#1]
What I would like (and what anyone using this for an editor would like) are these two procedures:

Ouput :: []Node;

1) `parse_project :: (path: string, config_options: []Config_Options) -> Output`
2) `update_file_contents :: (nodes: *Output, path: string, contents: string) -> result`

`parse_project` parses an entire jai project, returning everything.
`update_file_contents` takes the above data and amends it as if the specified file had the specified contents

**Comment by SogoCZE** [comment]
This interface will be provided in the future in [Jails](https://github.com/SogoCZE/Jails).
