### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by ArnaudValensi** [SogoCZE/jai_parser#2]
The following line seems invalid: https://github.com/SogoCZE/jai_parser/blob/main/parser.jai#L1198

![image](https://github.com/SogoCZE/jai_parser/assets/604486/2e60cfe2-3157-440e-b06a-1361eae926ce)

**Comment by SogoCZE** [comment]
This is now fixed. Thanks!

**Comment by ArnaudValensi** [comment]
Awesome, thanks!
