### ISSUE TITLE
Parser doesn't find modules folder if the jai compiler root is a directory not ending in "jai"

### ISSUE THREAD

**Issue by simonvanbernem** [SogoCZE/jai_parser#6]
I was seeing a lot of "Could not open file" messages when running the parser on my project. This turned out to be the case, because I renamed the compiler root directory from "jai" to "jai_compiler", which causes the parser to not find any modules directory.

**Comment by SogoCZE** [comment]
Fixed in https://github.com/SogoCZE/jai_parser/pull/5.
